# Generated by Django 3.1.5 on 2021-01-14 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sounds', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arousal', models.IntegerField(choices=[(0, 'No response'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('dominance', models.IntegerField(choices=[(0, 'No response'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('valence', models.IntegerField(choices=[(0, 'No response'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.emotionalsound')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.runsound')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'ordering': ['subject__subject_id', 'created_at'],
            },
        ),
    ]
